---
configRoots:
- extension:
    groupId: "io.github.yuokada.quarkus.extension"
    artifactId: "quarkus-fluency-fluentd"
    name: "Quarkus Fluency Fluentd"
    nameSource: "EXTENSION_METADATA"
    detected: true
  prefix: "quarkus.fluency"
  topLevelPrefix: "quarkus.fluency"
  items:
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "host"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.host"
      environmentVariable: "QUARKUS_FLUENCY_HOST"
    type: "java.lang.String"
    phase: "RUN_TIME"
    typeDescription: "string"
    defaultValue: "localhost"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "port"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.port"
      environmentVariable: "QUARKUS_FLUENCY_PORT"
    type: "int"
    phase: "RUN_TIME"
    typeDescription: "int"
    defaultValue: "24224"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "enabled"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.enabled"
      environmentVariable: "QUARKUS_FLUENCY_ENABLED"
    type: "boolean"
    phase: "RUN_TIME"
    typeDescription: "boolean"
    defaultValue: "true"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "senderMaxRetryCount"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.sender-max-retry-count"
      environmentVariable: "QUARKUS_FLUENCY_SENDER_MAX_RETRY_COUNT"
    type: "int"
    phase: "RUN_TIME"
    typeDescription: "int"
    defaultValue: "4"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "bufferChunkInitialSize"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.buffer-chunk-initial-size"
      environmentVariable: "QUARKUS_FLUENCY_BUFFER_CHUNK_INITIAL_SIZE"
    type: "int"
    phase: "RUN_TIME"
    typeDescription: "int"
    defaultValue: "1048576"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "bufferChunkRetentionSize"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.buffer-chunk-retention-size"
      environmentVariable: "QUARKUS_FLUENCY_BUFFER_CHUNK_RETENTION_SIZE"
    type: "int"
    phase: "RUN_TIME"
    typeDescription: "int"
    defaultValue: "4194304"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
    sourceElementName: "bufferChunkRetentionTimeMillis"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.fluency.buffer-chunk-retention-time-millis"
      environmentVariable: "QUARKUS_FLUENCY_BUFFER_CHUNK_RETENTION_TIME_MILLIS"
    type: "int"
    phase: "RUN_TIME"
    typeDescription: "int"
    defaultValue: "1000"
  qualifiedNames:
  - "io.github.yuokada.quarkus.extension.fluency.fluentd.runtime.FluencyConfig"
