# Fluentd connection settings — override these for your environment
quarkus.fluency.host=localhost
quarkus.fluency.port=24224
quarkus.fluency.enabled=true
quarkus.fluency.sender-max-retry-count=4
quarkus.fluency.buffer-chunk-initial-size=4194304
quarkus.fluency.buffer-chunk-retention-time-millis=1000
